Repository abdielzamudiov/JS-cheatsheet, pull requests merged in 2021-06, with the labels that each got.

#2 added docs
  Module 01/Lectures 01.md
  Module 02/Lectures 02.md
  Module 03/Lectures 03.md
  Tutorials.md
Labels: documentation

#4 testing if this fixes #3
  Module 01/README.md
Labels: invalid

#8 Finishing module 02
  Module 02/README.md
Labels: documentation

#9 Module03
  Module 03/Lectures 03.md
  Module 03/README.md
Labels: documentation

#12 Fix module03
  Module 03/README.md
Labels: enhancement

#19 readme 06 and challenges
  Challenges.md
  Module 06/Lectures 06.md
  Module 06/README.md
Labels: documentation

#21 Fix module01
  Module 01/README.md
Labels: enhancement

#24 module08 ready
  Module 08/Lectures 08.md
  Module 08/README.md
Labels: documentation

#25 Module09
  Module 09/Lectures 09.md
  Module 09/README.md
Labels: documentation
